// Code generated by "stringer -type=OpByte"; DO NOT EDIT

package nsync

import "fmt"

const _OpByte_name = "OpNoneOpDirUpdateOpFileUpdateOpKeepAliveOpFileRequest"

var _OpByte_index = [...]uint8{0, 6, 17, 29, 40, 53}

func (i OpByte) String() string {
	if i >= OpByte(len(_OpByte_index)-1) {
		return fmt.Sprintf("OpByte(%d)", i)
	}
	return _OpByte_name[_OpByte_index[i]:_OpByte_index[i+1]]
}
